### ISSUE TITLE
Make IIssue comparable

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues#128]
It would be nice to have the possibility to compare two `IIssue` instances

**Comment by marco-bertschi** [comment]
# Possiblities

## Let `IIssue` implement `IEquatable`
Pro:
- Done like it should be done
- Can compare two issues individually, given we follow MS' [Notes on how to implement `IEquatable<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.iequatable-1.equals?redirectedfrom=MSDN&view=netframework-4.8#notes-to-implementers)
- No additial `IEqualityComparer` needed, even when a `HashSet<IIssue>` is used.

Con:
- Breaking change

## Provide a default `IEqualityComparer<IIssue>`
Pro:
- No breaking change
- Can use a `HashSet<T>`, by setting it's `Comparer` property to the comparer for `IIssue` in order to union issues from multiple, partially overlapping providers (ex. DocFX + DocFX PDF Generator), without changing the `IIssue` interface
- The hash set can still be used if `IIssue` may implement `IEquatable` on day, and the comparer can potenatially be scrapped then (that's pro and con in one 💯 )

Con:
-  Two single issue instances can only be compared using the corresponding comparer, and not by the equality operator which would still compare on a referential basis.

Those two are what I feel like may be feasible, refrained on purpose to bring `IComparable` into this, since it's mostly about ordering than "Is this the same value?".

**Comment by pascalberger** [comment]
We can do a breaking change when releasing `0.8.0` (need to release all other addins in `0.8.0` version though. The main question for me between `IEquatable` vs `IEqualityComparer<IIssue>` is if we can set for a generic valid implementation of equality or is this something which is specific to the build script.

E.g. if you want to compare issues from the same build run you might want to to compare all fields of `IIssue`, on the other hand if you compare issues from different build runs, line might have change and you don't want to include it in the comparison.

Another implication of implementing `IEquatable` on `IIssue` is that the `Issue` class should be sealed (since it probably won't know how to implement equality for any derived classes.

**Comment by pascalberger** [comment]
@marco-bertschi I've created #139 which implements an `IEqualityComparer` for comparing issues and is ready for review. 

I decided against implementing `IEquatable` on `IIssue`. If  `IIssue` inherits from `IEquatable` this would enforce implementations (e.g. `Issue`) to implement it. If `==` operator on `Issue` is overloaded using `==` on `Issue` would do a value equality check, while using `==` on `IIssue` still would do a reference equality check, which IMHO would be confusing. Implementing `IEquatable` on `Issue` would make this clear, but probably won't help much, since most of the time an `IIssue` will be passed.
