### ISSUE TITLE
Merge Cake.Issues.Reporting and Cake.Issues.PullRequests into Cake.Issues

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues#204]
There's not much advantage to ship Cake.Issues.Reporting and Cake.Issues.PullRequests in separate release cycles. They don't bring any additional dependencies and just require an additional release cycle.

I would suggest to move them as additional projects into Cake.Issues, so that it still are three assemblies to have clean separation of responsibilities, but they are released and deployed in a single step.

Possible options:

1. Keep as it is now: Separate repos, separate addins, separate release cycles
2. Move into single repo, keep separate addins, released together. Allows user to still select what they want at runtime and won't be a breaking change.
3. Move into single repo, keep individual projects, deploy Cake.Issues.Reporting and Cake.Issues.PullRequests as part of Cake.Issues addin. Simplifies usage for user as it reduces number of addins. Is a breaking change.

**Comment by janniksam** [comment]
Personally, I don't mind having everything in one addin (option 3).
But I do agree with you, that PullRequests and Reports are optional features that are just built upon Cake.Issues and might be extended further and further in the future until we come to a point, where it doesn't belong into a single addin anymore.

From my perspective, it would be the best to start with option 2, because its a simple non-breaking change. If we do feel like merging them together in the future, we still can do it later on - even if we start "small" going for option 2.
