### ISSUE TITLE
Setting `FileLinkSettings` in `ReadIssueSettings` prevents any removal of file links by individual providers

### ISSUE THREAD

**Issue by hotchkj** [cake-contrib/Cake.Issues#716]
This may be a usage or abstraction issue, hard to be sure. Thoughts appreciated.

If as per examples I set up a `ReadIssues` alias call with settings of the form

``` csharp
var readSettings = new ReadIssuesSettings(_repoRootPath);
readSettings.FileLinkSettings = Context.IssueFileLinkSettingsForGitHubCommit(new Uri(_gitRepositoryUrl), _gitCommit);

ReadIssues(_providers, readSettings);
```

All of the reported `IIssue` entries get a malformed `FileLink` fragment even if the provider indicates there should be no file link.

For example, if a custom provider does the following:

``` csharp
// Does not set anything to do with paths as the issue is not linked to a specific file
return IssueBuilder.NewIssue<MyProvider>(message, this)
                   .WithFileLinkSettings(FileLinkSettings.ForAction(issue => { return null; }))
```

the resulting `IIssue` _still_ gets a malformed `FileLink` fragment that terminates in the Github hash.

Should the `FileLinkSettings` only be applied when the relative file path is known?

**Comment by pascalberger** [comment]
That's a good point. 

The current implementation will set file link settings when reading the issues directly after retrieving the items for the issue provider (https://github.com/cake-contrib/Cake.Issues/blob/4.10.0/src/Cake.Issues/IssuesReader.cs#L60-L68). Any potential value set by an issue provider will be overwritten. That the settings provided to the `ReadIssues` alias are winning over any potential value set by an issue provider does not necessarily seem wrong to me, since this is what the user explicitly asked for.

Based on the comment in the code snippet where you set the file link on the issue and your last question I assume your use case is that you have issues that don't link to files and you don't want to have a file link on them?

In this case IMHO the best solution would be to have the concrete `FileLinkOptionalSettingsBuilder` instance (in your example the `GitHubFileLinkSettingsBuilder`) return `null` if any of the information the builder requires to create a valid URL is missing (since the required information can be different for different builders). 
This should result that for issues which contain all required information for your file link builder to have a valid URL and issues which miss some information to contain `null`.

Would this approach solve your use case?

**Comment by hotchkj** [comment]
Apologies for the delay in reply - I will experiment with this approach, thanks very much for the detailed explanation and the proposed PR for future versions!

**Comment by pascalberger** [comment]
@hotchkj [4.10.1](https://github.com/cake-contrib/Cake.Issues/releases/tag/4.10.1) contains a fix that file links are no longer created when issue contains no file path.
